server {
    listen 80;
    
    # Configuração específica para a API do CDN
    location /api/cdn/ {
        # Tenta encontrar o arquivo estático primeiro
        try_files $uri $uri/ /index.html;
        
        # Se não encontrar, serve o index.html
        # Isso permitirá que o Nuxt.js lide com a rota da API
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    # Configuração padrão para o resto do site
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
