services:
  portfolio:
    image: portfolio:latest
    ports:
      - '3000:3000'
    environment:
      - CDN_API_KEY=${CDN_API_KEY}
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
