name: bot-code-reviewer

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    uses: RodolfoBonis/github-actions/.github/workflows/bot-code-reviewer.yml@main
    secrets:
      OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
