name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'version.txt'
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.setup-node.outputs.node-version }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js 🏗
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true

      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache node_modules and yarn cache 📦
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies 👨🏻‍💻
        run: yarn --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js 🏗
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node_version }}
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: yarn --frozen-lockfile

      - name: Run linter 👀
        run: yarn lint

  prettier:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js 🏗
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node_version }}
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: yarn --frozen-lockfile

      - name: Run Prettier 🖌
        run: yarn prettier:check

  sonar:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js 🏗
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node_version }}
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: yarn --frozen-lockfile

      - name: SonarQube Scan 🔍
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate 🚪
        uses: sonarsource/sonarqube-quality-gate-action@v2
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run script for Sonar metrics 📊
        if: ${{ github.event_name == 'pull_request' && always() }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          SONARQUBE_URL: ${{ secrets.SONAR_HOST_URL }}
          SONARQUBE_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONARQUBE_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPO_NAME: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python .config/scripts/generate_sonar_metrics_comment.py

      - name: Fail CI if Scan or Quality Gate fails ❌
        if: ${{ steps.sonar_scan.outcome == 'failure' || steps.sonar_quality_gate.outcome == 'failure' }}
        run: exit 1
