name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'version.txt'
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.setup-node.outputs.node-version }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js 🏗
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true

      - name: Cache node_modules 📦
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Configure Verdaccio Registry 🔐
        run: |
          echo "@rblab:registry=https://npm.rodolfodebonis.com.br" > .npmrc
          echo "//npm.rodolfodebonis.com.br/:_authToken=${{ secrets.VERDACCIO_TOKEN }}" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc

      - name: Install dependencies 👨🏻💻
        run: npm install

      - name: Build 🏗
        run: npm run build
