name: Generate PR Description

on:
  pull_request:
    types: [opened]

jobs:
  generate_description:
    uses: RodolfoBonis/github-actions/.github/workflows/generate-pr-description.yml@main
    secrets:
      OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
